# ╭──────────────────────────────────────ImplementationGuide───────────────────────────────────────╮
# │  The properties below are used to create the ImplementationGuide resource. For a list of       │
# │  supported properties, see: https://fshschool.org/docs/sushi/configuration/                    │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
id: johnmoehrke.slicingslicedextension
canonical: http://johnmoehrke.github.io/SlicingSlicedExtension
name: SlicingSlicedExtension
status: draft
version: 0.1.1-current
fhirVersion: 4.0.1
copyrightYear: 2022+
releaseLabel: ci-build
jurisdiction: 'http://unstats.un.org/unsd/methods/m49/m49.htm#804'
license: CC-BY-SA-4.0
description: "Showing a slicing of extension in a slice problem."
title: "Slicing sliced extension"
publisher:
  name: John Moehrke (himself)
  url: http://healthcaresecprivacy.blogspot.com
  email: JohnMoehrke@gmail.com
  
parameters:  # see https://confluence.hl7.org/display/FHIR/Implementation+Guide+Parameters
  path-resource:
    - input/resources
    - fsh-generated/resources
    - input/examples
#  path-pages:
#    - input/pagecontent
#    - fsh-generated/includes
  show-inherited-invariants: 'false'
  usage-stats-opt-out: 'false'
  logging: progress
  shownav: 'true'
  active-tables: 'false'
  apply-contact: 'true'
  apply-jurisdiction: 'true'
  apply-publisher: 'true'
  apply-version: 'true'

pages:
# itemize here each narrative page. Include assigned section numbers when appropriate
  index.md:
    title: Intro
    generation: markdown

  
# ╭────────────────────────────────────────────menu.xml────────────────────────────────────────────╮
# │  To use a provided input/includes/menu.xml file, delete the "menu" property below.             │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
menu:
  Home: index.html
  Artifacts: artifacts.html

